---
title: "Review of Laural Keat's Memory Study"
description: |
author:
  - name: Joseph Bulbulia
    url: https://josephbulbulia.netlify.app
    affiliation: Victoria University of Wellington
    affiliation_url: https://www.wgtn.ac.nz
    orcid_id: 0000-0002-5861-2056
date: June 2, 2021
output:
  distill::distill_article:
    self_contained: true
    toc: false
    code_folding: true
    highlight: tango
    highlight_downlit: false
bibliography: references.bib
---

```{r setup, include = FALSE}
# set up
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  echo = TRUE
)
```

```{r message = FALSE}
# required packages
if (!require(ggdag)) install.packages("ggdag")
```

## NOTES

Suppose we want to estimate the causal effect of episodic memory for depression. 

```{r graph1, layout="l-body-outset",  fig.height=8, fig.width=12}
# Graph model
library(ggdag)
dg_1<- ggdag::dagify(
  Depression2 ~   Memory1  + Depression1, 
  Memory2 ~ Memory1 + Depression2,
  exposure = "Memory1",
  outcome = "Depression2",
  labels = c(
    "Depression2" = "Depression2",
    "Memory1" = "Memory1",
    "Memory2" = "Memory2",
    "Depression1" = "Depression1"
   )
)#%>%
  #control_for(c("Memory2"))

p1 <-ggdag(dg_1, text = FALSE, use_labels = "label") + theme_dag_blank() + labs(title = "Proposed Causal Model for Externalising")
p1
ggdag::ggdag_collider(dg_1) + theme_dag_gray()

ggdag::ggdag_adjustment_set(dg_1) + theme_dag_gray()

```
