{
  "hash": "6954a0fa7c0997dcb54fdeccebf7699a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Review: RRBB-2024-0076 Quantifying Potential Selection Bias in Observational Research: Simulations and Analyses Exploring Religion and Depression Using a Prospective UK Cohort Study (ALSPAC)\"\nabstract: |\nauthor: \n  - name: Joseph A. Bulbulia\n    affiliation: Victoria University of Wellington, New Zealand\n    orcid_id: 0000-0002-5861-2056\n    email: joseph.bulbulia@vuw.ac.nz\neditor_options: \n  chunk_output_type: console\nformat:\n  pdf:\n    sanitize: true\n    keep-tex: true\n    link-citations: true\n    colorlinks: true\n    documentclass: article\n    classoption: [singlecolumn]\n    lof: false\n    lot: false\n    geometry:\n      - top=30mm\n      - left=20mm\n      - heightrounded\n    header-includes:\n      - \\input{/Users/joseph/GIT/latex/latex-for-quarto.tex}\ndate: last-modified\nexecute:\n  echo: true\n  warning: false\n  include: true\n  eval: true\nfontfamily: libertinus\nbibliography: /Users/joseph/GIT/templates/bib/references.bib\ncsl: /Users/joseph/GIT/templates/csl/camb-a.csl\n---\n\n\n\n\n\n## Decision\n\nMajor revisions required before considering for publication.\n\n## Summary\n\nThis submission addresses the critical issue of sample and target population mismatch, or \"selection bias.\" The authors specifically focus on the implications of panel attrition in a longitudinal study of pregnant women from Bristol in the early 1990s, examining the bias introduced when estimating the effects of religiosity on depression. The paper employs simulation and comparison of different datasets to evaluate problems of mismatch. \n\nDespite its merits, the manuscript contains methodological flaws that I believe preclude publication in its current form. However, with substantial revisions addressing the concerns outlined below, the study has the potential for publication.\n\n## Concerns and Recommendations\n\n1. **Methodological problems**: the study suffers from significant methodological issues. These issues must be thoroughly addressed in a revision.\n\n2. **Misuse of regression coefficients**: The authors rely on regression coefficients to evaluate threats to external validity, but this is misguided. This approach fails to account for treatment effect modification, leading to inaccurate assessments of bias. Below, I demonstrate the problem using a simulation. \n\n3. **Focus on marginal effect estimates**: a revised version of the paper should include a more robust analysis that accounts for the complexities of sample/target population mismatch and its implications estimating causal effects  They should include interaction terms when simulating data, and they should specifically evaluate whether differences in the distribution of effect-modifiers in the sample and target population lead to differences between sample and target population causal effect estimates. Anything less is arguably unrealistic for longitudinal research in the study of religion.\n\n4. **Encouragement**: despite the current shortcomings, the submission addresses an issue of considerable importance and widespread confusion. The authors should be encouraged to undertake the necessary revisions and resubmit their work. Appropriately considered findings will make a valuable contribution to the field.\n\n5. **Acknowledgment of fallibility**: I offer my review with the hope that it will assist the authors in strengthening their paper. I apologise if I have overlooked important details in their work.\n\n## Simulation to clarify the issues\n\nTo understand why we must focus on marginal effect estimates, consider the following simulation and analysis. \n\nFirst, we load the `stdReg` library, which obtains marginal effect estimates by simulating counterfactuals under different levels of treatment [@sjölander2016]. If a treatment is continuous, the levels can be specified. \n\nWe also load the `parameters` library, which creates nice tables [@parameters2020].\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# to obtain marginal effects\nlibrary(stdReg)\n# to create nice tables\nlibrary(parameters)\n```\n:::\n\n\n\nNext, we write a function to simulate data for the sample and and target populations. \n\nWe assume the treatment effect is the same in the sample and target population. We will assume that the coefficient for the effect-modifier and the coefficient for interaction are the same.  We assume no unmeasured confounding throughout the study.  We assume only selective attrition of one effect modifier such that the baseline population differs from the sample population at the end of the study.   \n\nThat is: **the distribution of effect modifiers is the only respect in which the sample will differ from the target population.**\n\nThis function will generate data under a range of scenarios.[^margot]\n\n[^margot]: See documentation in the `margot` package: @margot2024\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# function to generate data for the sample and population, \n# along with precise sample weights for the population, there are differences \n# in the distribution of the true effect modifier but no differences in the treatment effect \n# or the effect modification.all that differs between the sample and the population is \n# the distribution of effect-modifiers.\n\n\n# reproducability\nset.seed(123)\n\n\n# function based on margot::simulate_ate_data_with_weights, \n# see: https://go-bayes.github.io/margot/\n\nsimulate_ate_data_with_weights <- function(n_sample = 10000, # sample n\n                                           #population n\n                                           n_population = 100000,\n                                           # prob of effect modifier in sample\n                                           p_z_sample = 0.1,\n                                           #prob of effect modifier in the population\n                                           p_z_population = 0.5,\n                                           # treatment effect\n                                           beta_a = 1,\n                                           # coef of intervention\n                                           beta_z = 2.5,\n                                           # coef  of effect-modifier\n                                           beta_az = 0.5,\n                                           # effect modification of a by z\n                                           noise_sd = .5) {\n\n  # create sample data\n  z_sample <- rbinom(n_sample, 1, p_z_sample) # simulate data for sample z\n  a_sample <- rbinom(n_sample, 1, 0.5) # for sample treatment\n  \n  # simulate outcome\n  y_sample <- beta_a * a_sample + beta_z * z_sample + beta_az * (a_sample * z_sample) +\n    rnorm(n_sample, mean = 0, sd = noise_sd)  # use noise_sd for the noise term\n  \n  # put sample data in data frame\n  sample_data <- data.frame(y_sample, a_sample, z_sample)\n  \n  # simulate population data, where the distribution of effect modifiers differs, but the treatment effect is the same\n  z_population <- rbinom(n_population, 1, p_z_population)\n  a_population <- rbinom(n_population, 1, 0.5) # same effect of a on y \n  y_population <- beta_a * a_population + beta_z * z_population + \n    beta_az * (a_population * z_population) + rnorm(n_population, mean = 0, sd = noise_sd)  # noise\n  \n  # put population data in dataframe\n  population_data <- data.frame(y_population, a_population, z_population)\n  \n  # simulate weighting based on z distribution difference\n  weight_z_1 = p_z_population / p_z_sample # adjust weight for Z=1\n  weight_z_0 = (1 - p_z_population) / (1 - p_z_sample) # adjust weight for Z=0\n  weights <- ifelse(z_sample == 1, weight_z_1, weight_z_0)\n  \n  # add weights to sample_data\n  sample_data$weights = weights\n  \n  # return list of data frames and weights\n  list(sample_data = sample_data, population_data = population_data)\n}\n\n# simulate the data -- you can use different parameters\ndata <- simulate_ate_data_with_weights(\n  n_sample = 10000,\n  n_population = 100000,\n  p_z_sample = 0.1,\n  p_z_population = 0.5,\n  beta_a = 1,\n  beta_z = 2.5,\n  noise_sd = 0.5\n)\n```\n:::\n\n\n\nOk, we have generated both sample and population data. \n\n\nNext, we verify that the distributions of effect modifiers differ in the sample and in the target population:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# obtain the generated data\nsample_data <- data$sample_data\npopulation_data <- data$population_data\n\n\n# check imbalance\ntable(sample_data$z_sample) # type 1 is rare\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n   0    1 \n9055  945 \n```\n\n\n:::\n\n```{.r .cell-code}\ntable(population_data$z_population) # type 1 is common\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n    0     1 \n49916 50084 \n```\n\n\n:::\n:::\n\n\n\n\n\nGood, the distributions differ. The simulation is working as intended.\n\nNext, consider the question: \"What are the differences in the coefficients that we obtain from the study population at the end of study, as compared with the target population?\"  \n\n\nFirst, we obtain the coefficients for the sample. They are as follows:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# model coefficients sample\nmodel_sample  <-\n  glm(y_sample ~ a_sample * z_sample, data = sample_data)\n\n# summary\nparameters::model_parameters(model_sample, ci_method = \"wald\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nParameter           | Coefficient |       SE |        95% CI | t(9996) |      p\n-------------------------------------------------------------------------------\n(Intercept)         |   -6.89e-03 | 7.38e-03 | [-0.02, 0.01] |   -0.93 | 0.350 \na sample            |        1.01 |     0.01 | [ 0.99, 1.03] |   95.84 | < .001\nz sample            |        2.47 |     0.02 | [ 2.43, 2.52] |  104.09 | < .001\na sample × z sample |        0.51 |     0.03 | [ 0.44, 0.57] |   14.82 | < .001\n```\n\n\n:::\n:::\n\n\n\nOk, let's obtain the coefficients for the weighted regression of the sample.   Notice that the coefficients are virtually the same:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# model the sample weighted to the population, again note that these coefficients are similar \nmodel_weighted_sample <-\n  glm(y_sample ~  a_sample  * z_sample,\n      data = sample_data,\n      weights = weights)\n\n# summary\nsummary(parameters::model_parameters(model_weighted_sample, ci_method =\n                                       \"wald\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nParameter           | Coefficient |        95% CI |      p\n----------------------------------------------------------\n(Intercept)         |   -6.89e-03 | [-0.03, 0.01] | 0.480 \na sample            |        1.01 | [ 0.98, 1.04] | < .001\nz sample            |        2.47 | [ 2.45, 2.50] | < .001\na sample × z sample |        0.51 | [ 0.47, 0.55] | < .001\n\nModel: y_sample ~ a_sample * z_sample (10000 Observations)\nResidual standard deviation: 0.494 (df = 9996)\n```\n\n\n:::\n:::\n\n\n\n\nWe might be tempted to infer that weighting wasn't relevant to the analysis. However, we'll see that such an interpretation would be a mistake.\n\n\nNext, let us obtain model coefficients for the population. Note again there is no difference -- only narrower errors owing to the large sample size. \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# model coefficients population -- note that these coefficients are very similar. \nmodel_population <-\n  glm(y_population ~ a_population * z_population, data = population_data)\n\nparameters::model_parameters(model_population, ci_method = \"wald\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nParameter                   | Coefficient |       SE |        95% CI | t(99996) |      p\n----------------------------------------------------------------------------------------\n(Intercept)                 |    2.49e-03 | 3.18e-03 | [ 0.00, 0.01] |     0.78 | 0.434 \na population                |        1.00 | 4.49e-03 | [ 0.99, 1.01] |   222.35 | < .001\nz population                |        2.50 | 4.49e-03 | [ 2.49, 2.51] |   556.80 | < .001\na population × z population |        0.50 | 6.35e-03 | [ 0.49, 0.51] |    78.80 | < .001\n```\n\n\n:::\n:::\n\n\n\n\nAgain, there is no difference. That is, we find that all model coefficients are practically equivalent. The different distribution of effect modifiers does not result in different coefficient values for the treatment effect, the effect-modifier \"effect,\" or the interaction of effect modifier and treatment. \n\nConsider why this is the case: in a large sample where the causal effects are invariant -- as we have simulated them to be -- we will have good replication in the effect modifiers within the sample, so our statistical model can recover the *coefficients* for the population -- no problem. \n\nHowever, **in causal inference, we are interested in obtaining the marginal effect of the treatment**. That is, we seek an estimate for the counterfactual contrast in which everyone in a pre-specified population was subject to one level of treatment compared with a counterfactual condition in which everyone in a population was subject to another level of the same treatment. **When the sample population differs in the distribution of effect modifiers from the target population effect, the marginal effect estimates will typically differ.**\n\nTo see this, we use the `stdReg` package to recover marginal effect estimates, comparing (1) the sample ATE, (2) the true oracle ATE for the population, and (3) the weighted sample ATE.  We will use the outputs of the same models above. The only difference is that we will calculate marginal effects from these outputs. We will contrast a difference from an intervention in which everyone receives treatment = 0 with one in which everyone receives treatment = 1, however, this choice is arbitrary, and the general lessons apply irrespective of the estimand.\n\n\nFirst, consider this ATE for the sample population. \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# What inference do we draw?  We cannot say the models are unbiased for the marginal effect estimates. \n# regression standardisation \nlibrary(stdReg) # to obtain marginal effects \n\n\n# obtain sample ate\nfit_std_sample <-\n  stdReg::stdGlm(model_sample, data = sample_data, X = \"a_sample\")\n\n# summary\nsummary(fit_std_sample,\n        contrast = \"difference\",\n        reference = 0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nFormula: y_sample ~ a_sample * z_sample\nFamily: gaussian \nLink function: identity \nExposure:  a_sample \nReference level:  a_sample = 0 \nContrast:  difference \n\n  Estimate Std. Error lower 0.95 upper 0.95\n0     0.00     0.0000       0.00       0.00\n1     1.06     0.0101       1.04       1.08\n```\n\n\n:::\n:::\n\n\n\nThe treatment effect is given as a 1.06 unit change in the outcome across the sample population, with a confidence interval from 1.04 to 1.08. \n\n\nNext, we obtain the true (oracle) treatment effect for the population under the same intervention.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## note the population effect is different\n\n#obtain true ate\nfit_std_population <-\n  stdReg::stdGlm(model_population, data = population_data, X = \"a_population\")\n\n# summary\nsummary(fit_std_population,\n        contrast = \"difference\",\n        reference = 0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nFormula: y_population ~ a_population * z_population\nFamily: gaussian \nLink function: identity \nExposure:  a_population \nReference level:  a_population = 0 \nContrast:  difference \n\n  Estimate Std. Error lower 0.95 upper 0.95\n0     0.00    0.00000       0.00       0.00\n1     1.25    0.00327       1.24       1.26\n```\n\n\n:::\n:::\n\n\n\n\nBehold, the true treatment effect is a 1.25 unit change in the population, with a confidence bound between 1.24 and 1.26. This is well outside the ATE that we obtain from the sample population!\n\n\nNext, consider the ATE in the weighted regression, where the sample was weighted to the target population's true distribution of effect modifiers. \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## next try weights adjusted ate where we correctly assign population weights to the sample\nfit_std_weighted_sample_weights <- stdReg::stdGlm( model_weighted_sample, \n    data = sample_data, \n    X = \"a_sample\")\n\n# this gives us the right answer\nsummary(fit_std_weighted_sample_weights, \n    contrast = \"difference\", \n    reference = 0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nFormula: y_sample ~ a_sample * z_sample\nFamily: gaussian \nLink function: identity \nExposure:  a_sample \nReference level:  a_sample = 0 \nContrast:  difference \n\n  Estimate Std. Error lower 0.95 upper 0.95\n0     0.00     0.0000       0.00       0.00\n1     1.25     0.0172       1.22       1.29\n```\n\n\n:::\n\n```{.r .cell-code}\n# Moral of the story. When we marginalise over the entire sample we need to weight estimates to the target population. \n```\n:::\n\n\n\n\nGood news, we find that we obtain the population-level causal effect estimate with accurate coverage by weighting the sample to the target population. So with appropriate weights, our results generalise from the sample to the target population.\n\n\n## Lessons\n\n- Regression coefficients do not clarify the problem of sample/target population mismatch -- or selection bias as discussed in this manuscript.\n- The correct advice to investigators is that they should not rely on regression coefficients when evaluating the biases that arise from sample attrition. This advice applies to both methods that the authors use to investigate threats of bias. That is, to implement this advice, the authors must first take it.\n- Generally, observed data are insufficient for assessing threats. Observed data do not clarify structural sources of bias, nor do they clarify effect-modification in the full counterfactual data condition in which all receive the treatment and all do not receive the treatment (at the same level).\n- To properly assess bias, one would need access to the counterfactual outcome—what would have happened to the missing participants had they not been lost to follow-up or had they responded. Again, such counterfactual or \"full data\" are inherently unobservable [@vanderlaan2011]. \n- In simple settings like the one we just simulated, we may address the gap between the sample and target population using methods such as modelling the censoring (e.g., censoring weighting). However, we never know what setting we are in or whether it is simple—such modelling must be handled with care. There is a large and growing epidemiology literature on this topic (see, for example, @li2023non).\n- Matters become more complex when there is confounding and selection bias because the problem is not merely one of external validity but also internal validity (i.e. obtaining valid causal effect estimates for the baseline sample). See for example @scharfstein1999adjusting; @laan2003unified; @howe2016selection (note that @howe2016selection, \"selection\" bias is defined as collider stratification bias, a variety of confounding bias and not simple sample and target population mismatch.)  \n- Matters become more complex still in the presence of treatment-confounder feedback, for which only special methods are needed e.g. @rotnitzky2017multiply chapters in @van2012targeted.\n\n\n\n\n## Suggestions for revision\n\n### Assumptions and validity in specific contexts\n\n- I think the authors must clarify the conditions under which their methodology is applicable. Theoretically, if they wanted to retain the current analysis, they might acknowledge that their approach could hold under unverifiable assumptions of Missing Completely At Random (MCAR) and the absence of interactions. Although such a commentary may be relevant for biological inquiries, such as vaccine efficacy, where these assumptions might be more plausible, it seems rather doubtful in the study of religions. \n\n### Utility of regression coefficients\n\n- I recommend critically examining how regression coefficients may mislead in assessing external validity. By illustrating the problem through simulations—along the lines suggested here—the authors could offer a valuable perspective. Such an approach would not only elucidate the methodological pitfalls but also enrich understanding of sample/target population mismatch. For example, the authors could re-examine the assumptions of previous studies.\n\n\n### Address the \"Elephant in the Room\"\n\n- The discussion should extend to the broader implications of sample/target population mismatch beyond the immediate context of pregnant women in Bristol during the early 1990s. Highlighting this issue encourages clarity about assessing the generalisability of causal effect estimates. To date, the small but growing literature in this area has not been careful on this point.\n\nBy addressing these points, a substantially revised manuscript has the potential to make a substantive contribution to the literature on causal inference and its application to the study of religion and culture more generally.\n\n\n### Small Points \n\n#### 1. Abstract accuracy\n\n- Non-random participation is not a unitary phenomenon, but a spectrum of challenges. These include defining or selecting the target population, varying participation rates, nested vs. non-nested trial designs & others. The authors might find the following works helpful: @dahabreh2019 and @dahabreh2021study for randomised trials and @bareinboim2013general for observational studies.\n\n#### 2. Abstract is unclear\n\n- The abstract should promptly and clearly state the study's objective, focusing on the effect of church attendance on depression among the target population. The phrase \"despite non-random participation by the exposure and outcome\" is unclear because the meanings of these terms have yet to be defined.\n\n#### 3. Clarify the target population throughout\n\n- In abstract and throughout, clearly define the target population for ALSPAC at baseline, for example, as \"healthy pregnant women living in Bristol in the early 1990s\". Address the generalisation concern explicitly. \n\n#### 4. Revise redundant statements\n\n- For example, \"...with attendance at a place of worship associated with continued participation...\" This sounds like \"with attendance at a place of worship associated with attendance at a place of worship.\"\n\n#### 5. Simplify terminology \n\n- Consider consistently using a term such as \"composite religiosity\" instead of the acronym *RSBB* throughout the article for ease of understanding.\n\n#### 6. Clarify methodology\n\n- The introduction to the simulation approach should explicitly address potential concerns about effect modification and how it influences the study's findings.\n\n- If you retain comparative data analysis (I think you should not), explain each step of the analysis clearly. \n\n#### 7. Clarify rationale for variable selection\n\n- The rationale for selecting a limited number of variables from ALSPAC should be clearly explained. Arguably, a richer dataset is needed to assess effect-modification. Moreover, confounding would need to be addressed as well—if internal validity fails, so too will external validity. The authors cannot lose sight of confounding bias if their interest is in external validity. Again, I suggest simulating data in which a mismatch arises even without confounding bias.\n\n\n#### 9. Directed Acyclic Graph -- not persuasive, and probably not needed.\n\n- If you keep the DAG, make sure to avoid cycles (e.g., by indexing nodes by time); reconsider the credibility of the assumptions made, especially concerning effect modification by ethnicity (only through SEP and Marital Status)?  Again, problems arise even with unconfoundedness, as demonstrated above, so addressing confounding bias is insufficient to address threats to generalisation from attrition. A simple contribution would set confounding bias to the side.\n\n\n\n## References \n\n\n\n",
    "supporting": [
      "24-review-RRBB-2024-0076_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "\\usepackage{booktabs}\n\\usepackage{longtable}\n\\usepackage{array}\n\\usepackage{multirow}\n\\usepackage{wrapfig}\n\\usepackage{float}\n\\usepackage{colortbl}\n\\usepackage{pdflscape}\n\\usepackage{tabu}\n\\usepackage{threeparttable}\n\\usepackage{threeparttablex}\n\\usepackage[normalem]{ulem}\n\\usepackage{makecell}\n\\usepackage{xcolor}\n"
      ]
    },
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}